# Generated by Django 5.0.1 on 2024-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
